version: '3'
services:
  ## Postgres database for Backend Blog
  db-inventory:
    container_name: backend_db
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431